name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: |
            out
